### ISSUE TITLE
Merge two sorted Linked lists

### ISSUE THREAD

**Issue by vinayakkokane** [krishrahul98/DSA-Library#120]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Merge two sorted Linked lists

**Submission Type**
Data Structure

**Submission Description**
Added program for Merge two sorted Linked lists in C++

**Submission Directory**
Data structures => Linked Lists =>Merge_two_sorted_lists => mergeLists.cpp

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by krishrahul98** [comment]
@vinayakkokane Great, I have merged your PR.

**Comment by Siddhant-K-code** [comment]
Please Assign me for JavaScript

**Comment by krishrahul98** [comment]
> Please Assign me for JavaScript

@Siddhant-K-code Assigned for **Javascript**

**Comment by Abheetarora** [comment]
please assign this to me for java

**Comment by krishrahul98** [comment]
> please assign this to me for java

@Abheetarora Assigned for **Java**

**Comment by garg-saurav** [comment]
Please assign me for Python.

**Comment by garg-saurav** [comment]
Please assign me for Python

**Comment by krishrahul98** [comment]
> Please assign me for Python.

@garg-saurav Assigned for **Python**

**Comment by Dwarikanathmishra** [comment]
I would like to take up this issue to solve with C.

**Comment by krishrahul98** [comment]
> I would like to take up this issue to solve with C.

@Dwarikanathmishra Assigned for **C**

**Comment by Tanis-02** [comment]
Hi, I'd like to solve this in Java please

**Comment by krishrahul98** [comment]
> Hi, I'd like to solve this in Java please

@Tanis-02 Assigned for **Java**

**Comment by MayThirtyOne** [comment]
Hi, I would like to do this problem in C#. Please assign it to me.

Thank you.

**Comment by krishrahul98** [comment]
> Hi, I would like to do this problem in C#. Please assign it to me.
> 
> Thank you.

@MayThirtyOne Assigned for **C#**
