### ISSUE TITLE
Project Euler Problems Solutions

### ISSUE THREAD

**Issue by Siddhant-K-code** [krishrahul98/DSA-Library#125]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Project Euler/C++/1.cpp

**Submission Type**
Project Euler/C++

**Submission Description**
Describe the Problem

**Submission Directory**
Main_Folder => Sub_Folder => ... => ... => Filename.extension

**Language**

- [ ]  C++
- [ ]  C 
- [ ]  Python
- [ ] Java 
- [ ] C#
- [ ] JavaScript

[Problems List](https://projecteuler.net/archives)

**Comment by krishrahul98** [comment]
> We Can Also Start Contributing Project Euler Problems Solutions in Diff. Languages Like C/C++/Java/Python/JavaScript
> 
> [Problems List](https://projecteuler.net/archives)

@Siddhant-K-code Yes sure. Add a folder of Project Euler in the main directory and contributing.
It is a great idea.

**Comment by Siddhant-K-code** [comment]
@krishrahul98 can u pls create a proper issue with proper labels and directory, so we can proceed

**Comment by krishrahul98** [comment]
> @krishrahul98 can u pls create a proper issue with proper labels and directory, so we can proceed

@Siddhant-K-code ok sure. I will create a directory for this one and raise an issue.

**Comment by krishrahul98** [comment]
@Siddhant-K-code I have created a directory for Project Euler and raising and issue for that. 
So, I am closing this issue.

**Comment by krishrahul98** [comment]
@Siddhant-K-code 
#126  See this issue. I have added a proper working structure.
Start contributing 😃
