### ISSUE TITLE
Project Euler 21: Amicable Numbers 

### ISSUE THREAD

**Issue by garg-saurav** [krishrahul98/DSA-Library#133]
**Problem Link**
https://projecteuler.net/problem=21

**Submission Title**
Amicable Numbers

**Submission Type**
Algorithm

**Submission Description**
Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n). If d(a) = b and d(b) = a, where a ≠ b, then a and b are an amicable pair and each of a and b are called amicable numbers. Evaluate the sum of all the amicable numbers under 10000.

**Submission Directory**
Project_Euler => 21-Amicable_Numbers => Amicable_Numbers.language_extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by garg-saurav** [comment]
@krishrahul98 Please assign me for Python

**Comment by krishrahul98** [comment]
> @krishrahul98 Please assign me for Python

@garg-saurav Assigned for **Python**

**Comment by vieee** [comment]
Hi @krishrahul98, I would like to do this in C and Java, could I..?

**Comment by verma-shivani** [comment]
may you assign this to me for c++.

**Comment by marcelosdsouza** [comment]
Can you assign me C#?

**Comment by krishrahul98** [comment]
@marcelosdsouza Assigned for **C#**

@verma-shivani Assigned for **C++**

**Comment by marcelosdsouza** [comment]
Can you assign me JavaScript?

**Comment by krishrahul98** [comment]
> Can you assign me JavaScript?

@marcelosdsouza Assigned for **Javascript**
