### ISSUE TITLE
Quick Sort randomised.

### ISSUE THREAD

**Issue by lordinkavu** [krishrahul98/DSA-Library#147]
Add randomised quicksort in cpp. Also add randomised quicksort with 3 way partition, making the algorithm much more efficient in case of sequence with many equal elements.

**Submission Title**
Binary Search/Selection sort/Stacks

**Submission Type**
Algorithm/Data Structure

**Submission Description**
Describe the Algo/DS

**Submission Directory**
Main_Folder => Sub_Folder => ... => ... => Filename.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by krishrahul98** [comment]
@lordinkavu Great 👍🏼

**Comment by BellatrixLestrangee** [comment]
Would like to contribute for Java

**Comment by krishrahul98** [comment]
> Would like to contribute for Java

@BellatrixLestrangee Assigned for**Java**

**Comment by BellatrixLestrangee** [comment]
Can i contribute for Python too?

**Comment by krishrahul98** [comment]
> Can i contribute for Python too?

@BellatrixLestrangee Assigned for **Python**

**Comment by vieee** [comment]
Hi @krishrahul98, would like to contribute for C and C#

**Comment by krishrahul98** [comment]
> Hi @krishrahul98, would like to contribute for C and C#

@vieee Assigned for **C** and **C#**

**Comment by Bhavay192** [comment]
@krishrahul98  Assign me for JS

**Comment by krishrahul98** [comment]
> @krishrahul98 Assign me for JS

@Bhavay192 Assigned for **Javascript**
