### ISSUE TITLE
Level Order Traversal

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#163]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Level Order Traversal

**Submission Type**
Data Structure

**Submission Description**
Level order traversal of a tree is breadth-first traversal for the tree.

**Submission Directory**
Data_Structure => Tree => Binary_Tree_Level_Order_Traversal => Binary_Tree_Level_Order_Traversal.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [ ] C#
- [x] JavaScript

**Comment by avinashpai** [comment]
May I have C

**Comment by krishrahul98** [comment]
> May I have C

@avinashpai Assigned for **C**

**Comment by ChetanaL09** [comment]
Please Assign this to me for python

**Comment by shrutivasudevan** [comment]
Can you please assign this to me for Java

**Comment by krishrahul98** [comment]
> Please Assign this to me for python

@ChetanaL09 Assigned for **Python**

**Comment by krishrahul98** [comment]
> Can you please assign this to me for Java

@shrutivasudevan Assigned for **Java**

**Comment by MayThirtyOne** [comment]
Hi, I would like to do this problem in C++. Please assign it to me.

Thank you.

**Comment by jzhengcode** [comment]
Can you assign this to me for Javascript?

**Comment by krishrahul98** [comment]
> Hi, I would like to do this problem in C++. Please assign it to me.
> 
> Thank you.

@MayThirtyOne Assigned for **C++**

**Comment by krishrahul98** [comment]
> Can you assign this to me for Javascript?

@jzhengcode Assigned for **Javascript**

**Comment by MayThirtyOne** [comment]
Created a pull request. Thank you.

**Comment by MayThirtyOne** [comment]
Please review my pull request. Thank you.

**Comment by krishrahul98** [comment]
> Please review my pull request. Thank you.

@MayThirtyOne Done
