### ISSUE TITLE
Level Order Traversal in spiral form

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#164]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Level Order Traversal in the spiral form

**Submission Type**
Data Structure

**Submission Description**
Level order traversal of a tree is breadth-first traversal for the tree in Zig zag order.

**Submission Directory**
Data_Structure => Tree => Binary_Tree_Level_Order_Traversal_Spiral => Binary_Tree_Level_Order_Traversal_Spiral.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [ ] C#
- [ ] JavaScript

**Comment by SuyashDeshmukh** [comment]
Please assign it to me Java

**Comment by ChetanaL09** [comment]
Please assign this for me for Python

**Comment by krishrahul98** [comment]
> Please assign it to me for Java

@SuyashDeshmukh Assigned for **Java**

**Comment by krishrahul98** [comment]
> Please assign this for me for Python

@ChetanaL09 Assigned for **Python**

**Comment by vieee** [comment]
Hi @krishrahul98, I would like to do this in C, could you please assign it to me..?

**Comment by krishrahul98** [comment]
> Hi @krishrahul98, I would like to do this in C, could you please assign it to me..?

@vieee Assigned for **C**

**Comment by Radhamohan2** [comment]
please assign me for C++

**Comment by krishrahul98** [comment]
> please assign me for C++

@Radhamohan2 Assigned for **C++**
