### ISSUE TITLE
Linear Search

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#17]
Add comment to get assigned to your desired language.

**Submission Title**
Linear Search

**Submission Type**
Algorithm

**Submission Description**
Write Linear Search Algorithm

**Submission Directory**
Algorithm => Searching => Linear_Search => Linear_Search.extension

**Language**

- [x]  C++ 
- [x]  C 
- [x]  Python 
- [x] Java
- [x] JavaScript
- [x] C#

**Comment by sumasreeeduru** [comment]
hi could you assign me this? language: python

**Comment by krishrahul98** [comment]
> hi could you assign me this? language: python

Sure

**Comment by SanjayMarreddi** [comment]
@krishrahul98  I will do in It in C . Could you assign this to me

**Comment by Srithanya** [comment]
Could you assign me in Java?

**Comment by ritwiksingh21** [comment]
Hi, Can you assign me in C?

**Comment by krishrahul98** [comment]
> Hi, Can you assign me in C?

@ritwiksingh21 Please choose another language or another algorithm. C is already assigned.

**Comment by ritwiksingh21** [comment]
> > Hi, Can you assign me in C?
> 
> @ritwiksingh21 Please choose another language or another algorithm. C is already assigned.

sure.

**Comment by harsh0620** [comment]
Hey, can you assign me to C++?

**Comment by siddharthgangwar25** [comment]
Hello. Can I be assigned for C#?

**Comment by krishrahul98** [comment]
> Hello. Can I be assigned for C#?

Assigned @siddharthgangwar25

**Comment by Dwarikanathmishra** [comment]
I would like to try this with **JavaScript**.

**Comment by krishrahul98** [comment]
Completed
