### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#18]
Add comment to get assigned to your desired language.

**Submission Title**
Binary Search

**Submission Type**
Algorithm

**Submission Description**
Write Binary Search Algorithm

**Submission Directory**
Algorithm => Searching => Binary_Search => Binary_Search.extension

**Language**

- [x]  C++ 
- [x]  C 
- [x]  Python 
- [x] Java
- [x] JavaScript
- [x] C#

**Comment by falguni-k** [comment]
Hi. I can do it in c++. Can you assign it to me?

**Comment by shin-iji** [comment]
@krishrahul98 can i try in python?

**Comment by krishrahul98** [comment]
> @krishrahul98 can i try in python?

Sure. Assigning you to python

**Comment by krishrahul98** [comment]
> Hi. I can do it in c++. Can you assign it to me?

Sure

**Comment by arihantbansal** [comment]
I'll be implementing the algorithm in Java.

**Comment by Srithanya** [comment]
Could you assign Binary Search in C

**Comment by koshtaayush** [comment]
Hi @krishrahul98 , Can I please do it in Javascript ?

**Comment by krishrahul98** [comment]
> Hi @krishrahul98 , Can I please do it in Javascript ?

@koshtaayush Assigned for **Javascript**

**Comment by asamant** [comment]
Hi, @krishrahul98. Please assign C# to me.

**Comment by krishrahul98** [comment]
> Hi, @krishrahul98. Please assign C# to me.

@asamant Assigned for **C#**
