### ISSUE TITLE
String Permutations | Backtracking

### ISSUE THREAD

**Issue by swathi-vennela** [krishrahul98/DSA-Library#186]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
String Permutations

**Submission Type**
Algorithm

**Submission Description**
To write a program to find the permutations of a given string | Backtracking approach

**Submission Directory**
Algorithms => Backtracking => StringPermute.c => StringPermute.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by swathi-vennela** [comment]
Please assign me for C++

**Comment by krishrahul98** [comment]
> Please assign me for C++

@swathi-vennela Assigned for **C++* *

**Comment by anirudhps10** [comment]
Please assign me for python

**Comment by Bhavay192** [comment]
please assign me for java

**Comment by SrijitaSarkar99** [comment]
Please assign me for C

**Comment by krishrahul98** [comment]
> Please assign me for python

@anirudhps10 Assigned for **Python**

**Comment by krishrahul98** [comment]
> please assign me for java

@Bhavay192 Assigned for **Java**

**Comment by krishrahul98** [comment]
> Please assign me for C

@SrijitaSarkar99 Assigned for **C**

**Comment by Bhavay192** [comment]
please assign me for javascript

**Comment by jzhengcode** [comment]
Please assign me for Javascript

**Comment by cyenney** [comment]
can you assign to me in c#? Thank you.

**Comment by krishrahul98** [comment]
> Please assign me for Javascript

@jzhengcode Assigned for **Javascript**

**Comment by krishrahul98** [comment]
> can you assign to me in c#? Thank you.

@cyenney Assigned for **C#**
