### ISSUE TITLE
Linked List Loop detection | Floyd's cycle finding Algo

### ISSUE THREAD

**Issue by swathi-vennela** [krishrahul98/DSA-Library#187]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Linked List

**Submission Type**
Algorithm

**Submission Description**
Using the Floyd's Cycle finding algorithm to detect a loop/ cycle in a linked list

**Submission Directory**
Datastructures => Linkedlist => Linked_List_Cycle  => Filename.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by swathi-vennela** [comment]
Please assign me for C++

**Comment by krishrahul98** [comment]
> Please assign me for C++

@swathi-vennela Assigned for **C++**

**Comment by afflato** [comment]
Please assign me for Java

**Comment by krishrahul98** [comment]
> Please assign me for Java

@afflato Assigned for **Java**

**Comment by anirudhps10** [comment]
Please assign me to Python

**Comment by Radhamohan2** [comment]
please assign me for C

**Comment by krishrahul98** [comment]
> Please assign me to Python

@anirudhps10 Assigned for **Python**

**Comment by krishrahul98** [comment]
> please assign me for C

@Radhamohan2 Assigned for **C**

**Comment by afflato** [comment]
> > Please assign me for Java
> 
> @afflato Assigned for **Java**

Raised PR - #190

**Comment by krishrahul98** [comment]
> > > Please assign me for Java
> > 
> > 
> > @afflato Assigned for **Java**
> 
> Raised PR - #190

@afflato Done

**Comment by giribroba** [comment]
Please assign me for C#

**Comment by derekdkim** [comment]
Please assign me for Javascript

**Comment by krishrahul98** [comment]
> Please assign me for C#

@giribroba Assigned for **C#**

**Comment by krishrahul98** [comment]
> Please assign this issue to me for Javascript. I have the PR ready to go.

@derekdkim Assigned for **Javascript**
