### ISSUE TITLE
Interpolation Search

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#19]
Add comment to get assigned to your desired language.

**Submission Title**
Interpolation Search

**Submission Type**
Algorithm

**Submission Description**
Write Interpolation Search Algorithm

**Submission Directory**
Algorithm => Searching => Interpolation_Search => Interpolation_Search.extension

**Language**

- [x]  C++ 
- [x]  C 
- [x]  Python 
- [x] Java
- [ ] JavaScript
- [ ] C#

**Comment by falguni-k** [comment]
Hi, I can do it in c++. Can you assign it to me?

**Comment by suprimnakarmi** [comment]
Hey, I can do it in Python. Can you please assign it to me?

**Comment by suprimnakarmi** [comment]
I've created a directory for the Interpolation search in the required path, please update your code there. Thank you!

**Comment by krishrahul98** [comment]
> I've created a directory for the Interpolation search in the required path, please update your code there. Thank you!

Great

**Comment by vieee** [comment]
Hi @krishrahul98, could I do this in C and Java..?

**Comment by krishrahul98** [comment]
> Hi @krishrahul98, could I do this in C and Java..?

@vieee Assigned for **C** and **Java**
