### ISSUE TITLE
Inversion Count in an array 

### ISSUE THREAD

**Issue by swathi-vennela** [krishrahul98/DSA-Library#195]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Inversion Count of an array

**Submission Type**
Algorithm

**Submission Description**
Program to find the inversion count of an array

**Submission Directory**
Data_Structures => Array => Inversion_count  => Filename.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by swathi-vennela** [comment]
Please assign me for C++

**Comment by verma-shivani** [comment]
please assign me for c or c++

**Comment by Radhamohan2** [comment]
can you assign me for python

**Comment by giribroba** [comment]
please assign me for C#

**Comment by edinapap** [comment]
Hi, can you assign me for Javascript please?

**Comment by Shreyas-Gupta-21** [comment]
please assign me for c / c++

**Comment by Radhamohan2** [comment]
sorry by mistake I have done the PR before assignment of the issue.
Please assign me for python so that I can reopen the PR.

**Comment by krishrahul98** [comment]
> Please assign me for C++

@swathi-vennela Assigned for **C++**

**Comment by krishrahul98** [comment]
> please assign me for c or c++

@verma-shivani Assigned for **C**

**Comment by krishrahul98** [comment]
> can you assign me for python

@edinapap Assigned for **Python**

**Comment by krishrahul98** [comment]
> please assign me for C#

@giribroba Assigned for **C#**

**Comment by krishrahul98** [comment]
> Hi, can you assign me for Javascript please?

@edinapap Assigned for **Javascript**

**Comment by krishrahul98** [comment]
> please assign me for c / c++

@Shreyas-Gupta-21 hey you commented late. I am sorry but only java is left in this issue now.
Either choose java or raise your own issue with new topic.

**Comment by krishrahul98** [comment]
> sorry by mistake I have done the PR before assignment of the issue.
> Please assign me for python so that I can reopen the PR.

@Radhamohan2 Merged your PR

**Comment by Radhamohan2** [comment]
can you assign me for java also

**Comment by krishrahul98** [comment]
> can you assign me for java also

@Radhamohan2 Assigned for **Java**

**Comment by sourabhjain9887** [comment]
please assign me for c++

**Comment by krishrahul98** [comment]
> please assign me for c++

@sourabhjain9887  Assigned for **C++**. Don't use the logic that is already in another C++ implementation.

**Comment by sourabhjain9887** [comment]
added inversion-count in cpp

**Comment by krishrahul98** [comment]
> added inversion-count in cpp

@sourabhjain9887  I will merge your PR
