### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#2]
Add comment to get assigned to your desired language.

**Submission Title**
Selection Sort

**Submission Type**
Algorithm

**Submission Description**
Write Selection Sort Algorithm

**Submission Directory**
Algorithm => Sorting => Selection _Sort => Selection_Sort.extension

**Language**

- [x]  C++ 
- [x]  C 
- [x]  Python 
- [x] Java
- [x] JavaScript
- [x] C#

**Comment by sumasreeeduru** [comment]
assign me. Language: Python

**Comment by meghanagottapu** [comment]
can i work on this in java?

**Comment by krishrahul98** [comment]
> can i work on this in java?

Sure.

**Comment by anurag1299** [comment]
i want to do this in c#

**Comment by krishrahul98** [comment]
> i want to do this in c#

Sure

**Comment by ritwiksingh21** [comment]
Hi, can you assign me to do this in C?

**Comment by harsh0620** [comment]
Can I work on this in C++?

**Comment by krishrahul98** [comment]
> Can I work on this in C++?

Sure

**Comment by shailshah76** [comment]
Can i do it in JavaScript?

**Comment by krishrahul98** [comment]
> Can i do it in JavaScript?

@shailshah76 Assigned for **JavaScript**

**Comment by krishrahul98** [comment]
I am closing issue.
