### ISSUE TITLE
Jump Search

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#20]
Add comment to get assigned to your desired language.

**Submission Title**
Jump Search

**Submission Type**
Algorithm

**Submission Description**
Write Jump Search Algorithm

**Submission Directory**
Algorithm => Searching => Jump_Search => Jump_Search.extension

**Language**

- [x]  C++ 
- [ ]  C 
- [x]  Python 
- [x] Java
- [x] JavaScript
- [ ] C#

**Comment by BrianAnakPintar** [comment]
Hi, I would like to do it in python, can you assign it for me?

**Comment by ashima0699** [comment]
Hey! can you please assign this issue to me for c++

**Comment by krishrahul98** [comment]
> Hey! can you please assign this issue to me for c++

Assigned for **C++**

**Comment by vieee** [comment]
Hi @krishrahul98, I would like to code this in Java, could I..?

**Comment by krishrahul98** [comment]
> Hi @krishrahul98, I would like to code this in Java, could I..?

@vieee Assigned for **Java**

**Comment by BraveeSnow** [comment]
I can do this in js.

**Comment by krishrahul98** [comment]
> I can do this in js.

@BraveeSnow Assigned for **Javascript**
