### ISSUE TITLE
Longest Common Subsequence | DP

### ISSUE THREAD

**Issue by swathi-vennela** [krishrahul98/DSA-Library#220]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Longest Common Subsequence

**Submission Type**
Algorithm

**Submission Description**
Given two strings, find the longest common subsequence between them

**Submission Directory**
Algorithms => DP => Longest_Common_Subsequence =>  Filename.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [ ] C#
- [x] JavaScript

**Comment by krishrahul98** [comment]
@swathi-vennela Which language you want to choose?

**Comment by vieee** [comment]
Hi @krishrahul98, could you assign me for C and Java..?

**Comment by swathi-vennela** [comment]
> @swathi-vennela Which language you want to choose?

@krishrahul98  I can't work on this, this is just my attempt in encouraging people to contribute to dp..

**Comment by krishrahul98** [comment]
> > @swathi-vennela Which language you want to choose?
> 
> @krishrahul98 Thank you, but I can't work on this, this is just my attempt in encouraging people to contribute to dp..

Oh that's great

**Comment by krishrahul98** [comment]
> Hi @krishrahul98, could you assign me for C and Java..?

@vieee Assigned for **C** and **Java**

**Comment by sawyer1997** [comment]
For Python !✋🏻

**Comment by krishrahul98** [comment]
> For Python !✋🏻

@sawyer1997 Assigned for **Python**

**Comment by verma-shivani** [comment]
please assign me for c++

**Comment by krishrahul98** [comment]
> please assign me for c++

@verma-shivani Assigned for **C++**

**Comment by redgardner** [comment]
Can I take the Javascript part?

**Comment by krishrahul98** [comment]
> Can I take the Javascript part?

@redgardner Yes, Sure. You are assigned for **Javascript**.

**Comment by sourabhjain9887** [comment]
I would like to code in c++. Please assign me this issue.

**Comment by krishrahul98** [comment]
> I would like to code in c++. Please assign me this issue.

@sourabhjain9887 ok sure. Implement Memoization approach for this one because C++ is already assigned to someone.

**Comment by sawyer1997** [comment]
> > For Python !✋🏻
> 
> @sawyer1997 Assigned for **Python**

Please consider reviewing the code, and merging the same.

**Comment by krishrahul98** [comment]
> > > For Python !✋🏻
> > 
> > 
> > @sawyer1997 Assigned for **Python**
> 
> Please consider reviewing the code, and merging the same.

@sawyer1997 Done
