### ISSUE TITLE
nth Ugly Number | DP

### ISSUE THREAD

**Issue by swathi-vennela** [krishrahul98/DSA-Library#221]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
nth Ugly number | DP

**Submission Type**
Algorithm

**Submission Description**
Ugly numbers are numbers whose only prime factors are 2, 3 or 5. Given a number n, the task is to find n’th Ugly number.

**Submission Directory**
Algorithms => DP => nth_Ugly_Number =>  Filename.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by krishrahul98** [comment]
@swathi-vennela your language?

**Comment by Nitish-web-nik** [comment]
I want to contribute to this issue using C++ language, Please assign this to me.

**Comment by swathi-vennela** [comment]
> @swathi-vennela your language?

@krishrahul98  Thank you, but I can't work on this.. I just wanted to encourage people to contribute to dp..

**Comment by PRAy-d** [comment]
can i work on this issue?

**Comment by sawyer1997** [comment]
I can work in python, Golang, C/C++, and JavaScript on this one.

**Comment by krishrahul98** [comment]
> > @swathi-vennela your language?
> 
> @krishrahul98 Thank you, but I can't work on this.. I just wanted to encourage people to contribute to dp..

@swathi-vennela great

**Comment by krishrahul98** [comment]
> I want to contribute to this issue using C++ language, Please assign this to me. @krishrahul98 @swathi-vennela

@Nitish-web-nik Assigned for **C++**

**Comment by krishrahul98** [comment]
> can i work on this issue?

@PRAy-d your preferred language?

**Comment by krishrahul98** [comment]
> I can work in python, Golang, C/C++, and JavaScript on this one.

@sawyer1997 Assigned for **Python**, **Go**, **C** and **Javascript**

**Comment by verma-shivani** [comment]
Assign me this for java,please.

**Comment by krishrahul98** [comment]
> Assign me this for java,please.

@verma-shivani Assigned

**Comment by om840** [comment]
I want to contribute to this issue using Python  language, Please assign this to me.

**Comment by Amandixit10** [comment]
Hey ! i have gone through the issue an d finds it really interesting, i want to contribute the code, please assign me the issue.

**Comment by om840** [comment]
but how i can assign you i am also contributor

**Comment by krishrahul98** [comment]
> Hey ! i have gone through the issue an d finds it really interesting, i want to contribute the code, please assign me the issue in java.

@sawyer1997 Already someone is assigned for **Java**. So, I can't directly assign you to **Java**. I am assigning you for code with efficient time complexity. Just add efficient in your PR request and file name as well.
And don't forget to fill the PR template correctly. It helps a lot.

**Comment by krishrahul98** [comment]
@om840 I have gone through your PR. Your code is with very high complexity and already someone is assigned for **Python**. So, I can't accept your PR directly. Please write an efficient approach and append efficient in file name.
And fill the PR template properly.

**Comment by sawyer1997** [comment]
> > Hey ! i have gone through the issue an d finds it really interesting, i want to contribute the code, please assign me the issue in java.
> 
> @sawyer1997 Already someone is assigned for **Java**. So, I can't directly assign you to **Java**. I am assigning you for code with efficient time complexity. Just add efficient in your PR request and file name as well.
> And don't forget to fill the PR template correctly. It helps a lot.

@krishrahul98 I guess I have bee tagged in wrong reply?

**Comment by krishrahul98** [comment]
> > > Hey ! i have gone through the issue an d finds it really interesting, i want to contribute the code, please assign me the issue in java.
> > 
> > 
> > @sawyer1997 Already someone is assigned for **Java**. So, I can't directly assign you to **Java**. I am assigning you for code with efficient time complexity. Just add efficient in your PR request and file name as well.
> > And don't forget to fill the PR template correctly. It helps a lot.
> 
> @krishrahul98 I guess I have been tagged in wrong reply?

@sawyer1997 I am sorry. My bad.

**Comment by sawyer1997** [comment]
> > I can work in python, Golang, C/C++, and JavaScript on this one.
> 
> @sawyer1997 Assigned for **Python**, **Go**, **C** and **Javascript**

@krishrahul98 Please consider reviewing the PR, and merging the same.

**Comment by krishrahul98** [comment]
> > > I can work in python, Golang, C/C++, and JavaScript on this one.
> > 
> > 
> > @sawyer1997 Assigned for **Python**, **Go**, **C** and **Javascript**
> 
> @krishrahul98 Please consider reviewing the PR, and merging the same.

@sawyer1997 Done

**Comment by rachitmanas** [comment]
Can I take up the C# language?

**Comment by krishrahul98** [comment]
> Can I take up the C# language?

@rachitmanas Assigned for **C#**
Please follow all guidelines.
