### ISSUE TITLE
 UTF-8 encoding checker | bit-manipulation

### ISSUE THREAD

**Issue by Amandixit10** [krishrahul98/DSA-Library#228]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Bit-manipulation

**Submission Type**
Algorithm/Data Structure

**Submission Description**
Describe the Algo/DS

**Submission Directory**
Main_Folder => Sub_Folder => ... => ... => Filename.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [ ] C#
- [ ] JavaScript

**Comment by Amandixit10** [comment]
i want to contribute please assign this issue to me in java.

**Comment by jDerp** [comment]
I would like to contribute in C++. Please assign to me, Thank you.

**Comment by krishrahul98** [comment]
> i want to contribute please assign this issue to me in java.

@Amandixit10 Assigned for **Java**

**Comment by krishrahul98** [comment]
> I would like to contribute in C++. Please assign to me, Thank you.

@jDerp Assigned for **C++**

**Comment by rachitmanas** [comment]
I would like to contribute with Python3.  Can you please assign me @krishrahul98 ?

**Comment by krishrahul98** [comment]
> I would like to contribute with Python3. Can you please assign me @krishrahul98 ?

@rachitmanas Assigned for **Python**

**Comment by jDerp** [comment]
Do I need an assignment from you if I want to debug the python code?

**Comment by krishrahul98** [comment]
> Do I need an assignment from you if I want to debug the python code?

@jDerp if you want to debug and improve code it is great. It is better to get assigned. So, that we can keep track.

**Comment by jDerp** [comment]
So can you assign me on debugging the python code and also I want to add C implementation.

**Comment by krishrahul98** [comment]
> So can you assign me on debugging the python code and also I want to add C implementation.

@jDerp  Assigned for both.
