### ISSUE TITLE
Median-Of-Medians Algorithm | 

### ISSUE THREAD

**Issue by rachitmanas** [krishrahul98/DSA-Library#239]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Median_Of_Medians  algorithm

**Submission Type**
Algorithm
**Submission Description**
This algorithm can be used to find kth smallest number in any unsorted array in O(n), Linear time.

**Submission Directory**
Main_Folder => Sub_Folder => ... => ... => Filename.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [ ] Java 
- [ ] C#
- [x] JavaScript

**Comment by rachitmanas** [comment]
I would like to contribute in C++. Please assign me.

**Comment by krishrahul98** [comment]
> I would like to contribute in C++. Please assign me.

@rachitmanas Assigned for **C++**

**Comment by rachitmanas** [comment]
I have pulled the request. Please have a look and merge.

**Comment by krishrahul98** [comment]
> I have pulled the request. Please have a look and merge.

@rachitmanas Check your PR and comment.

**Comment by OussamaSALAHOUELHADJ** [comment]
Hey, I would like to implement the algorithm in JavaScript, please and thank you, I will give it a try.

**Comment by krishrahul98** [comment]
> Hey, I would like to implement the algorithm in JavaScript, please and thank you, I will give it a try.

@OussamaSALAHOUELHADJ You are assigned for **JavaScript**

**Comment by Priyanka11-dev** [comment]
Hi @krishrahul98 ,
Would like to try this with python.
Plz assign it to me.

**Comment by Kineolyan** [comment]
Hello @krishrahul98 I would like to be assigned to this task in C.

**Comment by hemanth-kotagiri** [comment]
@Kineolyan you are assigned for **C**.
