### ISSUE TITLE
Tim Sort | C, C++, Python, Java, JavaScript

### ISSUE THREAD

**Issue by hemanth-kotagiri** [krishrahul98/DSA-Library#240]
I would like to implement Tim Sort in all the languagues specified in the title. They are: C, C++, Java, Python and JavaScript

**Tim Sort**

**Submission Type**
Algorithm

**Submission Description**
Timsort is a hybrid stable sorting algorithm, derived from merge sort and insertion sort, designed to perform well on many kinds of real-world data. 
Here's more information from Wikipedia: [Tim Sort](https://en.wikipedia.org/wiki/Timsort)

**Submission Directory**
Algorithms => Sorting => Tim_Sort => tim_sort.c
Algorithms => Sorting => Tim_Sort => tim_sort.cpp
Algorithms => Sorting => Tim_Sort => tim_sort.py
Algorithms => Sorting => Tim_Sort => tim_sort.java
Algorithms => Sorting => Tim_Sort => tim_sort.js

**Language**

- [X]  C++
- [X]  C 
- [X]  Python
- [X]  Java 
- [ ]  C#
- [X]  JavaScript

**Comment by hemanth-kotagiri** [comment]
Please assign me the following languages for this task: C, CPP, Java, Python, JavaScript.
Thanks, @krishrahul98

**Comment by krishrahul98** [comment]
> Please assign me the following languages for this task: C, CPP, Java, Python, JavaScript. I will raise a PR pretty soon.
> Thanks, @krishrahul98

@hemanth-kotagiri Assigned for **C**, **C++**, **Java**, **Python** and **Javascript**.
