### ISSUE TITLE
Improve Contribution Guidelines | No Plagiarism

### ISSUE THREAD

**Issue by hemanth-kotagiri** [krishrahul98/DSA-Library#241]
This is not a bug-report, but rather an issue to improve this repository's contribution guidelines.

Please add **No Plagiarism** in the contribution guidelines to avoid PRs that directly copy-paste the code from elsewhere which is available from the internet.
My opinion is that an individual who's raising a PR should at-least have worked on it a bit before raising one but not merely copy-pasting it from elsewhere.
It's your wish @krishrahul98 to do the same. 

Please close this issue as soon as you resolve it with or without my suggestions.
Thanks!

**Comment by krishrahul98** [comment]
@hemanth-kotagiri Could you improve contributions guidelines and raise a PR. That will be a great help.
If you like to maintain this repository. I could add as a collaborator as well.

**Comment by hemanth-kotagiri** [comment]
@krishrahul98 That sounds awesome! Sure, I will raise a PR on the same. I am open to become a collaborator for this repository.
Thanks!

**Comment by krishrahul98** [comment]
@hemanth-kotagiri Ok I am making you collaborator.
