### ISSUE TITLE
Binary Insertion Sort | C, C++, Python, Java, JavaScript

### ISSUE THREAD

**Issue by hemanth-kotagiri** [krishrahul98/DSA-Library#254]
**Binary Insertion Sort**

**Algorithm**

**Submission Description**
Binary insertion sort uses a binary search to determine the correct location to insert new elements, and therefore performs ⌈log2 n⌉ comparisons in the worst case, which is O(n log n).
For More information: [Insertion Sort](https://en.wikipedia.org/wiki/Insertion_sort)

**Submission Directory**
``DSA-Library/Algorithms/Sorting/Binary_Insertion_Sort/``

**Language**

- [ ]  C++
- [ ]  C 
- [x]  Python
- [x] Java 
- [ ] C#
- [ ] JavaScript

**Comment by OussamaSALAHOUELHADJ** [comment]
Hey, I would like to implement the algorithm in C#, please, I will give it a try.

**Comment by krishrahul98** [comment]
> Hey, I would like to implement the algorithm in C#, please and thank you, I will give it a try.

@OussamaSALAHOUELHADJ You are assigned for **C#**

**Comment by ilmiye** [comment]
Can I get python one?

**Comment by hemanth-kotagiri** [comment]
Hey, @ilmiye. Go ahead. I will assign you for Python implementation.

**Comment by suraj-singh12** [comment]
Hi @hemanth-kotagiri , I would like to get the java version. Could you please assign me this?

**Comment by hemanth-kotagiri** [comment]
Go ahead @suraj-singh12. I'll assign you for Java.

**Comment by suraj-singh12** [comment]
@hemanth-kotagiri , kindly check the PR, I have added the Java version of Binary Insertion Sort.

**Comment by OussamaSALAHOUELHADJ** [comment]
@hemanth-kotagiri please check the PRs, I have included the JavaScript implementation of the Binary Insertion Sort algorithm, please and thank you.

**Comment by ilmiye** [comment]
Hey @hemanth-kotagiri can you check my PR #268 ?

**Comment by OussamaSALAHOUELHADJ** [comment]
@hemanth-kotagiri please check PRs, I have included the C# implementation of the Binary Insertion Sort algorithm, please and thank you. #269

**Comment by hemanth-kotagiri** [comment]
Sure, @OussamaSALAHOUELHADJ. I will check it out.

**Comment by Kineolyan** [comment]
Hello, the two languages being very similar, I would like to take this assignment for C **and** C++, if that's ok. Otherwise, assign me only C++.

**Comment by Kineolyan** [comment]
> Hello, the two languages being very similar, I would like to take this assignment for C and C++, if that's ok.
The PR for C is ready at #277. Considering the C++ version, for this particular algorithm, I don't see how much it is different from the C version. I can use C++ standard ways of printing values to the console. Would you like I use `vector` or `list` instead of a raw array?

**Comment by Neha2827** [comment]
Can I be assigned to this issue for C++?

**Comment by krishrahul98** [comment]
@PraSoonGosWami Try this one
