### ISSUE TITLE
Separate chaining - Hashing

### ISSUE THREAD

**Issue by Anthony-Citizen** [krishrahul98/DSA-Library#262]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Seperate Chaining

**Submission Type**
Data Structure

**Submission Description**
Separate chaining is defined as a method by which linked lists of values are built in association with each location within the hash table when a collision occurs. The figure shows incidences of collisions in different table locations.

**Submission Directory**
Data_Structures => Hashing => SeperateChaining.c

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [ ] C#
- [x] JavaScript

**Comment by hemanth-kotagiri** [comment]
@krishrahul98 I will pick up other languages such as Python, C++, Java, and JavaScript.

**Comment by ilmiye** [comment]
Can I get python one?

**Comment by krishrahul98** [comment]
> @krishrahul98 I will pick up other languages such as Python, C++, Java, and JavaScript.

@hemanth-kotagiri yes sure go ahead. Leave **Python** for @ilmiye

**Comment by krishrahul98** [comment]
> Can I get python one?

@ilmiye Assigned for **Python**
