### ISSUE TITLE
Adding Disjoint set union (UNION FIND) implementation.

### ISSUE THREAD

**Issue by khushbooSingh99** [krishrahul98/DSA-Library#266]
**Submission Title**
Disjoint Set Union

**Submission Type**
Data Structure

**Submission Description**
Describe the DS

**Submission Directory**
Main_Folder => Data_Structures => Union Find => dsu_implementation.cpp

**Language**

- [x]  C++
- [ ]  C 
- [ ]  Python
- [ ] Java 
- [ ] C#
- [ ] JavaScript

Please assign me this issue.

**Comment by khushbooSingh99** [comment]
Please assign me this issue.

**Comment by krishrahul98** [comment]
> Please assign me this issue.

@khushbooSingh99 assigned for **C++**

**Comment by amintai** [comment]
Can i work with JavaScript? @krishrahul98

**Comment by OussamaSALAHOUELHADJ** [comment]
@khushbooSingh99  can you please assign it to me in Javascript, thankyou

**Comment by hemanth-kotagiri** [comment]
Hey, @amintai. I am assigning you the implementation in JavaScript.

**Comment by OussamaSALAHOUELHADJ** [comment]
@hemanth-kotagiri can you assign me for C# please and thank you.

**Comment by OussamaSALAHOUELHADJ** [comment]
@hemanth-kotagiri please check the PRs #271 , I have included the C# implementation of the Disjoint-set (UNIONFIND) Data Structure, please and thank you.
