### ISSUE TITLE
Add Coded triangle numbers Problem Number 42

### ISSUE THREAD

**Issue by divyanshutw** [krishrahul98/DSA-Library#273]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Problem Link**
https://www.hackerrank.com/contests/projecteuler/challenges/euler042/
https://projecteuler.net/problem=42

**Submission Title**
Project Euler Coded triangle numbers Problem Number 42

**Submission Type**
Algorithm

**Problem Description**
The nth term of the sequence of triangle numbers is given by, tn = ½n(n+1). By converting each letter in a word to a number corresponding to its alphabetical position and adding these values we form a word value. If the word value is a triangle number then we shall call the word a triangle word.

**Submission Directory**
Project_Euler => 42-Coded triangle numbers => Coded triangle numbers.cpp

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [ ] C#
- [ ] JavaScript

Kindly assign me this issue.
Thanks

**Comment by krishrahul98** [comment]
@rahul2001dewangan Python assigned to you.
