### ISSUE TITLE
Kadane's algorithm - Typescript

### ISSUE THREAD

**Issue by PraSoonGosWami** [krishrahul98/DSA-Library#285]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Kadane's algorithm - Typescript - DP

**Submission Type**
Algorithm

**Submission Description**
The algorithm is used for finding a contiguous subarray with the largest sum, within a given one-dimensional array A[1...n] of numbers

**Submission Directory**
DSA-Library/Algorithms/DP/Kadane-algorithm/index.ts

**Language**

- [x]  C++
- [ ]  C 
- [ ]  Python
- [ ] Java 
- [x] C#
- [ ] JavaScript
- [X] TypeScript

**Comment by krishrahul98** [comment]
@PraSoonGosWami PR merged.

**Comment by g4m3r0** [comment]
Kindly assign me the C# part.

**Comment by krishrahul98** [comment]
@rahul2001dewangan C++ assigned to you.

**Comment by krishrahul98** [comment]
@g4m3r0 C# assigned to you
