### ISSUE TITLE
Insertion sort

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#3]
Add comment to get assigned to your desired language.

**Submission Title**
Insertion Sort

**Submission Type**
Algorithm

**Submission Description**
Write Insertion Sort Algorithm

**Submission Directory**
Algorithm => Sorting => Insertion _Sort => Insertion_Sort.extension

**Language**

- [x]  C++ 
- [x]  C 
- [x]  Python 
- [x] Java
- [x] JavaScript
- [x] C#

**Comment by jayaganeshkumar** [comment]
I want to do this sorting in C, C++ and Python. Can you assign it to me?
@krishrahul98

**Comment by krishrahul98** [comment]
@jayaganeshkumar Assigned you. Write code and upload in the proper directory. :)

**Comment by jayaganeshkumar** [comment]
@krishrahul98  I have submitted a PR with the programs. Check it and merge.

**Comment by krishrahul98** [comment]
@jayaganeshkumar Your PR is merged already.

**Comment by jayaganeshkumar** [comment]
Thank you @krishrahul98

**Comment by harsh0620** [comment]
Can I work on this in Java?

**Comment by krishrahul98** [comment]
> Can I work on this in Java?

Sure

**Comment by BrianAnakPintar** [comment]
Can I work on this for c#

**Comment by krishrahul98** [comment]
> Can I work on this for c#

Assigned for C#

**Comment by shailshah76** [comment]
I can implement it in JavaScript

**Comment by krishrahul98** [comment]
> I can implement it in JavaScript

@shailshah76 Assigned for **Javascript**

**Comment by krishrahul98** [comment]
Closing issue.
