### ISSUE TITLE
Bucket Sort

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#34]
Add comment to get assigned to your desired language.

**Submission Title**
Bucket Sort

**Submission Type**
Algorithm

**Submission Description**
Write the Bucket Sort Algorithm

**Submission Directory**
Algorithm => Sorting => Bucket _Sort => Bucket_Sort.extension

**Language**

- [x]  C++ 
- [x]  C 
- [x]  Python 
- [x] Java
- [x] JavaScript
- [ ] C#

**Comment by ritwiksingh21** [comment]
Hello. I would like to be assigned to do this in C.

**Comment by Priyanshi-3** [comment]
I would like to do this in java. Can you please assign it to me?

**Comment by krishrahul98** [comment]
> I would like to do this in java. Can you please assign it to me?

@Priyanshi-3 
Assigned for **Java**

**Comment by Priyanshi-3** [comment]
#103 BucketSort.java created. Please review.

**Comment by krishrahul98** [comment]
> #103 BucketSort.java created. Please review.

Done

**Comment by Abheetarora** [comment]
please assign this to me for cpp

**Comment by krishrahul98** [comment]
> please assign this to me for cpp

@Abheetarora Assigned for **C++**

**Comment by leli-1** [comment]
Can you assing this to me for python language

**Comment by krishrahul98** [comment]
> Can you assing this to me for python language

@leli-1 Assigned for **Python**

**Comment by Neha2827** [comment]
> Add comment to get assigned to your desired language.
> 
> **Submission Title**
> Bucket Sort
> 
> **Submission Type**
> Algorithm
> 
> **Submission Description**
> Write the Bucket Sort Algorithm
> 
> **Submission Directory**
> Algorithm => Sorting => Bucket _Sort => Bucket_Sort.extension
> 
> **Language**
> 
> * [x]   C++
> * [x]   C
> * [x]   Python
> * [x]  Java
> * [ ]  JavaScript
> * [ ]  C#

**Comment by Neha2827** [comment]
Can you assign this to me for JAVA

**Comment by krishrahul98** [comment]
> Can you assign this to me for JAVA

@Neha2827 Assigned for **Java**. Someone already submitted in **Java**, please name your file little different.

**Comment by redgardner** [comment]
Can I take this for Javascript?

**Comment by krishrahul98** [comment]
@redgardner Assigned for **Javascript**

**Comment by ilmiye** [comment]
Please check https://github.com/krishrahul98/DSA-Library/pull/279 @krishrahul98 @hemanth-kotagiri

**Comment by Neha2827** [comment]
can you assign it for c++?
