### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#4]
Add comment to get assigned to your desired language.

**Submission Title**
Bubble Sort

**Submission Type**
Algorithm

**Submission Description**
Write the Bubble Sort Algorithm

**Submission Directory**
Algorithm => Sorting => Bubble _Sort => Bubble_Sort.extension

**Language**

- [x]  C++ 
- [x]  C 
- [x]  Python 
- [x] Java
- [x] JavaScript
- [x] C#

**Comment by anurag1299** [comment]
I want to do this in java

**Comment by krishrahul98** [comment]
> I want to do this in java

Sure

**Comment by asunawesker** [comment]
Hi can you assing this to me in C?

**Comment by krishrahul98** [comment]
> Hi can you assing this to me in C?

Sure

**Comment by sumasreeeduru** [comment]
Hi could you assign me this in python.

**Comment by krishrahul98** [comment]
> Hi could you assign me this in python.

Sure

**Comment by confusedcoder1** [comment]
Hey, can you assign this to me for javascript or C++?

**Comment by krishrahul98** [comment]
> Hey, can you assign this to me for javascript or C++?

Sure. Follow folder structure for PR @confusedcoder1

**Comment by Lemorz56** [comment]
Hey, I could do bubble sort for C++ 😎. Can you assign me to it?

**Comment by avinashpai** [comment]
Can I get C?

**Comment by krishrahul98** [comment]
> Can I get C?

@avinashpai Assigned for **C**

**Comment by nzubair** [comment]
Hi, I'd like to try my hands on C#.  Can you please assign?

**Comment by krishrahul98** [comment]
> Hi, I'd like to try my hands on C#. Can you please assign?

@nzubair Assigned for **C#**
