### ISSUE TITLE
Array Rotation

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#40]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Array Rotation (Left or Right)

**Submission Type**
Data Structure

**Submission Description**
Write a program to rotate an array of size n by k elements (Left or Right).

**Submission Directory**
Data_Structures => Array => Rotate_Array_L.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by falguni-k** [comment]
Hi! I would like to do it in c++. Please assign.

**Comment by siddharthgangwar25** [comment]
Can I try it in Python? I'm new to python and would love to contribute with it.

**Comment by krishrahul98** [comment]
> Can I try it in Python? I'm new to python and would love to contribute with it.

Sure

**Comment by PrajaktaS23** [comment]
I want to implement this in java

**Comment by krishrahul98** [comment]
> I want to implement this in java

Assigned for Java

**Comment by Siddhant-K-code** [comment]
Please Assign Me for `JavaScript`

**Comment by krishrahul98** [comment]
> Please Assign Me for `JavaScript`

@Siddhant-K-code Assigned for **Javascript**

**Comment by Siddhant-K-code** [comment]
@krishrahul98  Please assign me for **C**

**Comment by krishrahul98** [comment]
> @krishrahul98 Please assign me for **C**

@Siddhant-K-code Assigned for **C**

**Comment by Ashutoshnegi880** [comment]
please, assign me this in c#

**Comment by krishrahul98** [comment]
> please, assign me this in c#

@Ashutoshnegi880 Assigned for **C#**
