### ISSUE TITLE
Array Reversal 

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#42]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Array Reversal

**Submission Type**
Data Structure

**Submission Description**
Write a program to reverse an array of size n. Apply any algorithm of your choice.

**Submission Directory**
Data_Structures => Array => Reverse_Array_AlgorithmName.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by therc01** [comment]
Hi, i can reverse the array in **Python**

**Comment by ritwiksingh21** [comment]
Hi, can you assign me to do this in C?

**Comment by therc01** [comment]
hi, also assign it to me in C++, thanks

**Comment by krishrahul98** [comment]
> hi, also assign it to me in C++, thanks

Yes, you can do. 👍🏼

**Comment by siddharthgangwar25** [comment]
Can I be assigned for Java?

**Comment by Siddhant-K-code** [comment]
Please Assign Me for `JavaScript`

**Comment by krishrahul98** [comment]
> Please Assign Me for `JavaScript`

@Siddhant-K-code Assigned for ** Javascript **

**Comment by Aaditree** [comment]
Hi, can you assign C# to me?
Thanks.

**Comment by krishrahul98** [comment]
> Hi, can you assign C# to me?
> Thanks.

@Aaditree Assigned for **C#**.
After completing this, remind me to close this issue.

**Comment by Aaditree** [comment]
> > Hi, can you assign C# to me?
> > Thanks.
> 
> @Aaditree Assigned for **C#**.
> After completing this, remind me to close this issue.

Completed and pulled the request.

**Comment by krishrahul98** [comment]
> > > Hi, can you assign C# to me?
> > > Thanks.
> > 
> > 
> > @Aaditree Assigned for **C#**.
> > After completing this, remind me to close this issue.
> 
> Completed and pulled the request.

Thanks for reminding.
