### ISSUE TITLE
Search Element in sorted and rotated array

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#43]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Sorted and Rotated Array Search

**Submission Type**
Data Structure

**Submission Description**
Write a program to search an array of size n where the array is sorted and rotated by k.

**Submission Directory**
Data_Structures => Array => Rotated_Array_Search.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by vieee** [comment]
Hi @krishrahul98, I would like to code this in C

**Comment by krishrahul98** [comment]
> Hi @krishrahul98, I would like to code this in C

Sure

**Comment by PrajaktaS23** [comment]
I want to implement this in python

**Comment by krishrahul98** [comment]
> I want to implement this in python

Assigned for Python

**Comment by AnkitaM84** [comment]
Hey! I would like to take this up in Java.
Thank you

**Comment by krishrahul98** [comment]
> Hey! I would like to take this up in Java.
> Thank you

Assigned for **Java**

**Comment by Aaditree** [comment]
Hi, I would like to code this in C++

**Comment by krishrahul98** [comment]
> Hi, I would like to code this in C++

@Aaditree Assigned for **C++**

**Comment by Aaditree** [comment]
> > Hi, I would like to code this in C++
> 
> @Aaditree Assigned for **C++**

Done and pulled the request.

**Comment by krishrahul98** [comment]
> > > Hi, I would like to code this in C++
> > 
> > 
> > @Aaditree Assigned for **C++**
> 
> Done and pulled the request.

Yes I have merged your PR.

**Comment by asamant** [comment]
Hi, @krishrahul98, please assign C# to me.

**Comment by krishrahul98** [comment]
> Hi, @krishrahul98, please assign C# to me.

@asamant Assigned for **C#**

**Comment by Bhavay192** [comment]
Hi , please assign me for JavaScript

**Comment by krishrahul98** [comment]
> Hi , please assign me for JavaScript

@Bhavay192 Assigned for **Javascript**

**Comment by sourabhjain9887** [comment]
I would like to code this in c++. Please assign me this issue.

**Comment by krishrahul98** [comment]
> I would like to code this in c++. Please assign me this issue.

@sourabhjain9887 In **C++** code is already implemented. Please choose another issue or raise a new one with your choice of DSA problem.
