### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#5]
Add comment to get assigned to your desired language.

**Submission Title**
Quick Sort

**Submission Type**
Algorithm

**Submission Description**
Write Quick Sort Algorithm

**Submission Directory**
Algorithm => Sorting => Quick _Sort => Quick_Sort.extension

**Language**

- [x]  C++ 
- [x]  C 
- [x]  Python 
- [x] Java
- [x] JavaScript
- [x] C#

**Comment by anurag1299** [comment]
i want to do this in java

**Comment by Srithanya** [comment]
Can you assign me quick sort in python?

**Comment by ritwiksingh21** [comment]
Hi, Can you assign me in C?

**Comment by jayaganeshkumar** [comment]
Hi, can I submit the code for this in C++? If yes, assign to me?

**Comment by SaloniK17** [comment]
Hii, can you please assign me quick sort in c?
Thank you.

**Comment by krishrahul98** [comment]
> Hii, can you please assign me quick sort in c?
> Thank you.
@SaloniK17 
Quick Sort in C is already added to the repository. If you can write another version of quicksort like **Randomized** Quicksort then I can assign you or choose any other thing to contribute. If you want to contribute a new thing you can raise an issue. I will be happy to help.

**Comment by koshtaayush** [comment]
Hi @krishrahul98 , Can I please do this in Javascript ?

**Comment by krishrahul98** [comment]
> Hi @krishrahul98 , Can I please do this in Javascript ?

@koshtaayush Assigned for **Javascript**

**Comment by nzubair** [comment]
Hi, I'd like to try my hands on C#.  Can you please assign?

**Comment by krishrahul98** [comment]
> Hi, I'd like to try my hands on C#. Can you please assign?

@nzubair Assigned for **C#**
