### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#6]
Add comment to get assigned to your desired language.

**Submission Title**
Merge Sort

**Submission Type**
Algorithm

**Submission Description**
Write Merge Sort Algorithm

**Submission Directory**
Algorithm => Sorting => Merge _Sort => Merge_Sort.extension

**Language**

- [x]  C++ 
- [x]  C 
- [x]  Python 
- [x] Java
- [x] JavaScript
- [x] C#

**Comment by Nikzy7** [comment]
I can do this in c++, java and python ! please assign me this issue 😄

**Comment by krishrahul98** [comment]
> I can do this in c++, java and python ! please assign me this issue

Ok assigning you for C++, Java, Python.

**Comment by SanjayMarreddi** [comment]
Hey @krishrahul98 Could you assign me this for C ?

**Comment by debarshi-1999** [comment]
I want to implement this in C++. Can you please assign me this?

**Comment by therc01** [comment]
Hi, i want to create program for merge sort in python,

**Comment by rishika-singh49** [comment]
Hi, i want to create program for merge sort in c . will you please assign me......

**Comment by harsh0620** [comment]
Can I work on this in Java?

**Comment by krishrahul98** [comment]
> Hi, i want to create program for merge sort in c . will you please assign me......

@rishika-singh49 
merge sort in C is already assigned and added to the repository before. If you want to add a modified version of Merge sort in C then I can assign you. you can choose any other thing of your choice and if it is not in issue, you can always raise a new issue and get assigned.

**Comment by krishrahul98** [comment]
> Can I work on this in Java?

Assigned for Java

**Comment by shailshah76** [comment]
I can do it in JavaScript

**Comment by krishrahul98** [comment]
> I can do it in JavaScript

@shailshah76 Assigned for **JavaScript**

**Comment by vieee** [comment]
Hi @krishrahul98, I want to implement this in C#. Could you please assign me this?

**Comment by krishrahul98** [comment]
> Hi @krishrahul98, I want to implement this in C#. Could you please assign me this?

@vieee Assigned for **C#**
