### ISSUE TITLE
Implement Stack

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#63]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Stack Implementation

**Submission Type**
Data Structure

**Submission Description**
Implement Stack form scratch

**Submission Directory**
Dat_Structures => Stack => Stack_Implementation.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by avinashpai** [comment]
May i complete this in C?

**Comment by krishrahul98** [comment]
> May i complete this in C?

Assigned for C

**Comment by PrajaktaS23** [comment]
I want to implement this in java

**Comment by krishrahul98** [comment]
> I want to implement this in java

Assigned for Java

**Comment by Danotsonof** [comment]
Could you assign this to me for C#.

**Comment by krishrahul98** [comment]
> Could you assign this to me for C#.

Assigned for C#

**Comment by Harshalszz** [comment]
Hey! can I work on this in C++ and Python.

**Comment by krishrahul98** [comment]
> Hey! can I work on this in C++ and Python.

Assigned for **Cpp* and **Python**

**Comment by Siddhant-K-code** [comment]
Please Assign me for `JavaScript`

**Comment by krishrahul98** [comment]
> Please Assign me for `JavaScript`

Assigned for **Javascript**

**Comment by Siddhant-K-code** [comment]
#108 Will *Completely Close* This Issue

**Comment by krishrahul98** [comment]
> #108 Will _Completely Close_ This Issue

@Siddhant-K-code Yes, I am closing this issue.
