### ISSUE TITLE
Implement Queue

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#64]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Queue Implementation

**Submission Type**
Data Structure

**Submission Description**
Implement Queue form scratch

**Submission Directory**
Dat_Structures => Queue => Queue_Implementation.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by shailshah76** [comment]
could you assign  it to me?
I'll be able to implement it in C++

**Comment by krishrahul98** [comment]
> could you assign it to me?
> I'll be able to implement it in C++

Done

**Comment by EANimesha** [comment]
Assign me to implement in C

**Comment by krishrahul98** [comment]
> Assign me to implement in C

Assigned for C

**Comment by BraveeSnow** [comment]
I could try implementing this in java.

**Comment by PrajaktaS23** [comment]
I want to implement this in python

**Comment by krishrahul98** [comment]
> I could try implementing this in java.

Assigned for Java

**Comment by krishrahul98** [comment]
> I want to implement this in python

Assigned for Python

**Comment by Danotsonof** [comment]
Could you assign this to me for C#.

**Comment by krishrahul98** [comment]
> Could you assign this to me for C#.

Assigned for C#

**Comment by Siddhant-K-code** [comment]
Please Assign me for `JavaScript`

**Comment by krishrahul98** [comment]
> Please Assign me for `JavaScript`

@Siddhant-K-code Assigned for **Javascript**

**Comment by krishrahul98** [comment]
> I want to implement this in python

@PrajaktaS23 Not completed yet.

**Comment by krishrahul98** [comment]
> could you assign it to me?
> I'll be able to implement it in C++

@shailshah76 Not Completed yet.

**Comment by krishrahul98** [comment]
**C++** and **Python** available.

**Comment by shailshah76** [comment]
I'll complete it by tomorrow i am working on it

**Comment by krishrahul98** [comment]
> I'll complete it by tomorrow i am working on it

Ok then assigning you for *C++**

**Comment by Siddhant-K-code** [comment]
can i work on Python ?

**Comment by krishrahul98** [comment]
> can i work on Python ?

@Siddhant-K-code Assigned for **Python**

**Comment by krishrahul98** [comment]
Closing issue.
