### ISSUE TITLE
Implement Binary Search Tree

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#65]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Binary Search Tree

**Submission Type**
Data Structure

**Submission Description**
Implement Binary Search Tree

**Submission Directory**
Data_Structures => Tree => BST_Implementation =>  Binary_Search_Tree.extension

**Language**

- [x]  C++
- [x]  Python
- [x] Java 
- [x] C#
- [ ] JavaScript

**Comment by EANimesha** [comment]
I like to complete in java, python and javascript

**Comment by krishrahul98** [comment]
> I like to complete in java, python and javascript

Assigned for Java, Python and Javascript @EANimesha

**Comment by jayaganeshkumar** [comment]
@krishrahul98  I like to contribute the code in C++. If you agree, assign it to me.

**Comment by krishrahul98** [comment]
> @krishrahul98 I like to contribute the code in C++. If you agree, assign it to me.

Assigned for C++

**Comment by jayaganeshkumar** [comment]
@krishrahul98  I made a pull request, check it and merge it and label as "hacktober-accepted"

**Comment by krishrahul98** [comment]
> @krishrahul98 I made a pull request, check it and merge it and label as "hacktober-accepted"

Done

**Comment by SaloniK17** [comment]
hii  ,can you please assign this issue to me for c?
Thank you

**Comment by krishrahul98** [comment]
> hii ,can you please assign this issue to me for c?
> Thank you

**C** is already contributed by someone else. Only **C#** is available. You can choose either **C#** or choose another issue. 
If you like you can create a **new** issue for something else, there are lots of options.

**Comment by SaloniK17** [comment]
shall i make a non-recursive(traversal funtion ) program in c ?

**Comment by krishrahul98** [comment]
> shall i make a non-recursive(traversal funtion ) program in c ?

#93 
@SaloniK17 Check Issue no #93  I have assigned you there for Binary Tree Traversal Iterative version in **C**.

**Comment by nzubair** [comment]
Can you please assign C#?

**Comment by krishrahul98** [comment]
> Can you please assign C#?

@nzubair Assigned for **C#**

**Comment by nzubair** [comment]
@krishrahul98  It seems like there are two different folders for BST.  `Data_Structures => Tree => BST_Implementation` and `Data_Structures => Tree => BST`.   Would it be OK if you I moved the two files in `BST` into `BST_Implementation` as part of my PR?

**Comment by krishrahul98** [comment]
> @krishrahul98 It seems like there are two different folders for BST. `Data_Structures => Tree => BST_Implementation` and `Data_Structures => Tree => BST`. Would it be OK if you I moved the two files in `BST` into `BST_Implementation` as part of my PR?

@nzubair yes, it is ok. Improvement is always welcome.
