### ISSUE TITLE
Heap Sort

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#7]
Add comment to get assigned to your desired language.

**Submission Title**
Heap Sort

**Submission Type**
Algorithm

**Submission Description**
Write Heap Sort Algorithm

**Submission Directory**
Algorithm => Sorting => Heap _Sort => Heap_Sort.extension

**Language**

- [x]  C++ 
- [x]  C 
- [x]  Python 
- [x] Java
- [x] JavaScript
- [x] C#

**Comment by Nikzy7** [comment]
Hey I can do this in C++, java and python !

**Comment by krishrahul98** [comment]
> Hey I can do this in C++, java and python !

Assigned you for C++, Java, Python

**Comment by anurag1299** [comment]
Hey I want to do this in c and c#

**Comment by krishrahul98** [comment]
> Hey I want to do this in c and c#

Sure

**Comment by leli-1** [comment]
Can you assign this to me for python ?

**Comment by krishrahul98** [comment]
> Can you assign this to me for python ?

@leli-1 Assigned for **Python**

**Comment by BraveeSnow** [comment]
I can do this in C++.

**Comment by krishrahul98** [comment]
> I can do this in C++.

@BraveeSnow Assigned for **C++**

**Comment by Neha2827** [comment]
Can you assign to me for C?

**Comment by krishrahul98** [comment]
> Can you assign to me for C?

@Neha2827 Assigned for **C**

**Comment by redgardner** [comment]
Can I take this for Javascript?

**Comment by krishrahul98** [comment]
> Can I take this for Javascript?

@redgardner Assigned for **Javascript**

**Comment by krishrahul98** [comment]
**Python** available.

**Comment by ilmiye** [comment]
Hey, can you assign python part of this issue to me?

**Comment by krishrahul98** [comment]
> Hey, can you assign python part of this issue to me?

@ilmiye Assigned for **Python**

**Comment by SaloniK17** [comment]
Hey, can you assign c part of this issue to me ?

**Comment by ilmiye** [comment]
Hey @krishrahul98 , Can you check my PR #275 ?

**Comment by ilmiye** [comment]
Please check #278 @krishrahul98 @hemanth-kotagiri

**Comment by Neha2827** [comment]
can you assign this for c++
