### ISSUE TITLE
Counting Sort

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#8]
Add comment to get assigned to your desired language.

**Submission Title**
Counting Sort

**Submission Type**
Algorithm

**Submission Description**
Write Counting Sort Algorithm

**Submission Directory**
Algorithm => Sorting => Counting _Sort => Counting_Sort.extension

**Language**

- [x]  C++ 
- [x]  C 
- [x]  Python 
- [x] Java
- [ ] JavaScript
- [x] C#

**Comment by sumasreeeduru** [comment]
assign me. Language: Python

**Comment by BraveeSnow** [comment]
I can try writing the algorithm in C++.

**Comment by Srithanya** [comment]
assign me. Langauge: Python

**Comment by krishrahul98** [comment]
@Srithanya Python is already assigned to @sumasreeeduru .
Please choose some other language or choose another sorting from issues or create a new issue.

**Comment by Srithanya** [comment]
assign me. Language: C

**Comment by Amulya-coder** [comment]
I wants to work on Java.

**Comment by Ashutoshnegi880** [comment]
assign me in c#

**Comment by krishrahul98** [comment]
> assign me in c#

@Ashutoshnegi880 Assigned for **C#**
