### ISSUE TITLE
Reverse Linked List

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#81]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Reverse Linked List

**Submission Type**
Data Structure

**Submission Description**
Reverse given linked list either recursively or iteratively.

**Submission Directory**
Data_Structures => LinkedList => Reverse_List => Reverse_Linked_List.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by krishrahul98** [comment]
C++ code is already in the repository.

**Comment by AnkitaM84** [comment]
Hey! I would like to work on this in Java.
Thank you

**Comment by Dwarikanathmishra** [comment]
I would like to work on this in C.

**Comment by krishrahul98** [comment]
> Hey! I would like to work on this in Java.
> Thank you

Assigned for **Java**

**Comment by krishrahul98** [comment]
> I would like to work on this in C.

Assigned for **C**

**Comment by asamant** [comment]
Please assign C# to me.

**Comment by krishrahul98** [comment]
> Please assign C# to me.

Assigned for **C#**

**Comment by Siddhant-K-code** [comment]
Please Assign me for `JavaScript` *&* `Python`

**Comment by krishrahul98** [comment]
> Please Assign me for `JavaScript` _&_ `Python`

@Siddhant-K-code Assigned for **Javascript** and **Python**

**Comment by Siddhant-K-code** [comment]
#113 Will Completely Close This Issue

**Comment by krishrahul98** [comment]
> #113 Will Completely Close This Issue

@Siddhant-K-code Person assigned to **C** not completed it yet.

**Comment by krishrahul98** [comment]
> I would like to work on this in C.

@Dwarikanathmishra not completed yet.

**Comment by Dwarikanathmishra** [comment]
Created Pull request #134 in response to the assigned work. Apologies for the delay.

**Comment by krishrahul98** [comment]
> Created Pull request #134 in response to the assigned work. Apologies for the delay.

No problem. @Dwarikanathmishra
