### ISSUE TITLE
Rotate Linked List

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#82]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Submission Title**
Rotate Linked List by K

**Submission Type**
Data Structure

**Submission Description**
Given a linked list, rotate the list to the right by k places, where k is non-negative.

**Submission Directory**
Data_Structures => LinkedList => Rotate_Linked_List => Rotate_Linked_List.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by krishrahul98** [comment]
C++ code is already in the repository.

**Comment by asamant** [comment]
Please assign C to me.

**Comment by krishrahul98** [comment]
> Please assign C to me.

Assigned for **C**

**Comment by AnkitaM84** [comment]
Hey! I would like to take this up in Java.

**Comment by krishrahul98** [comment]
> Hey! I would like to take this up in Java.

Assigned for **Java**

**Comment by AnkitaM84** [comment]
@krishrahul98 in the instructions it says "commit the changes with appropriate msg". What exactly has to be written in the message? Asking beforehand to avoid any confusion

**Comment by Siddhant-K-code** [comment]
Please Assign `JavaScript` to me

**Comment by krishrahul98** [comment]
> Please Assign `JavaScript` & `Python` to me

Assigned for **JavaScript** and **Python**

**Comment by krishrahul98** [comment]
Just Add commit message like what you are adding or what you are changing.

**Comment by krishrahul98** [comment]
> @krishrahul98 in the instructions it says "commit the changes with appropriate msg". What exactly has to be written in the message? Asking beforehand to avoid any confusion

@AnkitaM84 
Just Add commit message like what you are adding or what you are changing that would be fine.

**Comment by asamant** [comment]
Please assign C# to me.

**Comment by krishrahul98** [comment]
> Please assign C# to me.

@asamant Assigned for **C#**
