### ISSUE TITLE
Binary Tree Traversal (PreOrder,InOrder,PostOrder)

### ISSUE THREAD

**Issue by krishrahul98** [krishrahul98/DSA-Library#93]
Add comment to get assigned to your desired language.
Follow Submission directory Structure for PR merge.

**Get Assigned for either iterative or recursive or both**.

**Submission Title**
Preorder, InOrder and PreOrder Binary Tree Traversal

**Submission Type**
Algorithm/Data Structure

**Submission Description**
Write all three Binary Tree Traversal either iterative or recursive. 

**Submission Directory**
Data_Structures => Tree => Binary_Tree_Traversal => Binary_Tree_Traversal_Iterative/Recursive.extension

**Language**

- [x]  C++
- [x]  C 
- [x]  Python
- [x] Java 
- [x] C#
- [x] JavaScript

**Comment by krishrahul98** [comment]
@SaloniK17 
Comment here to get assigned for **C Iterative**

**Comment by AbhinavGor** [comment]
Can I do C implementation for pre, post and in orders?  @krishrahul98

**Comment by vmarpadge** [comment]
Hi
Can you Assign me this for Java?

**Comment by Rohit-2602** [comment]
@krishrahul98 can i work on it (in java)

**Comment by krishrahul98** [comment]
> Hi
> Can you Assign me this for Java?

Assigned for **Java Iterative and Recursive**

**Comment by krishrahul98** [comment]
> @krishrahul98 can i work on it (in java)

If you want to work on iterative implementation then i can assign you **Java**. You are always free to choose any other language or algorithm or data structure of your choice. If it is not in issue raise an issue and get assigned.

**Comment by Rohit-2602** [comment]
> > @krishrahul98 can i work on it (in java)
> 
> If you want to work on iterative implementation then i can assign you **Java**. You are always free to choose any other language or algorithm or data structure of your choice. If it is not in issue raise an issue and get assigned.

Yes i can do iterative implementation in java..
And if possible in c also..

**Comment by krishrahul98** [comment]
@Rohit-2602 Assigned for **Java Iterative** and **C iterative**

**Comment by SaloniK17** [comment]
Can you asaigm to me this issue for c?

**Comment by SaloniK17** [comment]
Can you assign to me this issue for c both recursive and iterative?

**Comment by krishrahul98** [comment]
> Can you assign to me this issue for c both recursive and iterative?

Assigned for **C Both**

**Comment by Rohit-2602** [comment]
@krishrahul98 I am not able to find Binary_Tree folder... plzzz help
Implemented successfully...

**Comment by krishrahul98** [comment]
> @krishrahul98 I am not able to find Binary_Tree folder... plzzz help
> Implemented successfully...

Create Binary_Tree folder under Tree then save your code there and push.

**Comment by valar-yudha** [comment]
hey, can you assign this to me for C++ (recursive) ?

**Comment by krishrahul98** [comment]
> hey, can you assign this to me for C++ (recursive) ?

@valar-yudha Assigned for **C++ recursive**

**Comment by Priyanshi-3** [comment]
Can you assign this to me for both iterative and recursive in python?

**Comment by krishrahul98** [comment]
> Can you assign this to me for both iterative and recursive in python?

@Priyanshi-3 Assigned for **Python both**

**Comment by avinashpai** [comment]
Can you assign me C++ iterative?

**Comment by krishrahul98** [comment]
> Can you assign me C++ iterative?

@avinashpai Assigned for **C++ iterative**

**Comment by Priyanshi-3** [comment]
BST_recursive in python #159

**Comment by Priyanshi-3** [comment]
BST_iterative in python #161

**Comment by krishrahul98** [comment]
@Priyanshi-3 both PR is merged. Great Work 👍🏼 
From next time please fill the PR template correctly.

**Comment by MayThirtyOne** [comment]
Hi, I would like to do this problem in C#. Please assign it to me.

Thank you.

**Comment by krishrahul98** [comment]
> Hi, I would like to do this problem in C#. Please assign it to me.
> 
> Thank you.

@MayThirtyOne Assigned for **C#**
